### ISSUE TITLE
Integration with nova-permission

### ISSUE THREAD

**Issue by iBet7o** [tightenco/parental#20]
I am trying to integrate this package together with [nova-permission](https://github.com/vyuldashev/nova-permission) and apparently it is not compatible or something I am doing wrong.

This is my Admin model

```php
...

use Spatie\Permission\Traits\HasRoles;
use Tightenco\Parental\HasParentModel;

class Admin extends User
{
    use HasRoles;

    use HasParentModel;
}
```

and my Admin resource

```php
...

    public function fields(Request $request)
    {
        return [
            ...
            MorphToMany::make('Roles', 'roles', \Vyuldashev\NovaPermission\Role::class),
            MorphToMany::make('Permissions', 'permissions', \Vyuldashev\NovaPermission\Permission::class),
        ];
    }

...

```

**Error: Class name must be a valid object or a string**

**Comment by calebporzio** [comment]
I have not tried using Parental with Nova/nova-permission. Can you post a full stack trace? Maybe I can catch something from that.

**Comment by adriandmitroca** [comment]
Hey guys,

I've faced a similar issue to this one. Turns out that when creating a model object, Parental transforms it into Child Model (so for example, an Admin model instead of a User model) when Nova, obviously, expects it to be actual `User` object.

Specifically, this line causes conflict with Nova: https://github.com/tightenco/parental/blob/master/src/ReturnsChildModels.php#L13

Since Nova is official Laravel tool, perhaps a dirty solution to bypass Parental stuff from Nova requests would be good?

For now, I've overriden `newInstance` method using pretty simple workaround:

```php
$model = isset($attributes[$this->getInhertanceColumn()]) && !str_contains(url()->current(), Nova::path())
            ? $this->getChildModel($attributes)
            : new static(((array) $attributes));
```

@calebporzio, would you like to get a PR with this or would you have some better solution in mind?

Not gonna lie, this isn't perfect as in this situation it wouldn't be possible to create child models on Nova side at all, but right now it is quite unfunctional.

**Comment by calebporzio** [comment]
Interesting, thanks for posting a solution @adriandmitroca. Unfortunately, I haven't dug into Nova yet to really know the implications of pulling in that workaround. I will try to address this sometime this week - stay tuned.

**Comment by adriandmitroca** [comment]
Just for a heads up - during further work with Parental and Nova I had to revert back entities to child model (via helper function) in some context (basically when triggering some custom logic in Actions) to make sure all application logic is being executed as it should be (eg. triggering child-specific notifications).

To be honest, I don't have perfect idea how to solve that issue.
